ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'All' do

  #pod 'CocoaAsyncSocket', '~> 7.6.2'
  pod 'CocoaAsyncSocket', :git => 'https://github.com/robbiehanson/CocoaAsyncSocket.git'

  pod 'Alamofire', '~> 4.6.0'
  pod 'AlamofireObjectMapper', '~> 5.0.0'

  pod 'RealmSwift', '~> 3.0.2'

  pod 'XCGLogger', '~> 6.0.2'
  #pod 'BrightFutures', '~> 6.0.0'

  target 'RMBTClient_iOS' do
    platform :ios, '9.0'

    # Pods for RMBTClient_iOS
    pod 'GCNetworkReachability', '~> 1.3.2'
  end
  
  target 'UnitTests' do
      # Pods for RMBTClient_iOS
      pod 'GCNetworkReachability', '~> 1.3.2'
  end

  target 'RMBTClient_OSX' do
    platform :osx, '10.11'

    # Pods for RMBTClient_OSX
    pod 'GCNetworkReachability', '~> 1.3.2'
  end

  target 'RMBTClient_tvOS' do
    platform :tvos, '9.2'

    # Pods for RMBTClient_tvOS
    # TODO: GCNetworkReachability
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['XCGLogger', 'Realm', 'RealmSwift'].include? "#{target}"
            print "Setting #{target}'s SWIFT_VERSION to 4.0\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
            else
            print "Setting #{target}'s SWIFT_VERSION to Undefined (Xcode will automatically resolve)\n"
            target.build_configurations.each do |config|
                config.build_settings.delete('SWIFT_VERSION')
            end
        end
    end
    
    print "Setting the default SWIFT_VERSION to 3.2\n"
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.2'
    end
end
