ENV['COCOAPODS_DISABLE_STATS'] = 'true'

platform :ios, '9.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'All' do

  pod 'RMBTClient', :path => '../rmbt-ios-client'

  pod 'CocoaAsyncSocket', :git => 'https://github.com/robbiehanson/CocoaAsyncSocket.git'

  pod 'TUSafariActivity', '~> 1.0.4'
  pod 'GoogleMaps', '~> 2.6.0'
  pod 'BCGenieEffect', '~> 1.1'
  pod 'KINWebBrowser', '~> 1.3.2'
  #pod 'KLCPopup', '~> 1.0' # PopupKit?
  
  pod 'PopupDialog', '~> 0.6.2' # TODO: git clone fails because of slow download: '~> 0.7.1'

  pod 'ActionKit', '~> 2.3.2'

  # lib for autolayout contraints
  #pod 'SnapKit', '~> 3.1.2'

  #pod 'SWRevealViewController', '~> 2.3.0' # TODO: not possible to use the version from cocoapods because tb changed something in the implementation...
  #pod 'MMDrawerController', '~> 0.5.7'

  #pod 'BrightFutures', '~> 1.0.0'

  # For graphs
  #pod 'Charts', '~> 3.0.1'

  pod 'SwiftGen', '~> 5.2.1'
  pod 'SwiftLint', '~> 0.24.2'
  pod 'BartyCrouch', '~> 3.8.1'

  target 'RMBT_ILR' do
      
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['RMBTClient', 'XCGLogger', 'Realm', 'RealmSwift'].include? "#{target}"
            print "Setting #{target}'s SWIFT_VERSION to 4.0\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        else
            print "Setting #{target}'s SWIFT_VERSION to Undefined (Xcode will automatically resolve)\n"
            target.build_configurations.each do |config|
                config.build_settings.delete('SWIFT_VERSION')
            end
        end
    end

    print "Setting the default SWIFT_VERSION to 3.2\n"
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.2'
    end
end
