import Foundation

///
let ICON_FONT_NAME = "alladin-icons"

/////

// TODO: ILR design

let ILR_WHITE = UIColor.white
let ILR_LIGHT_GRAY = UIColor(rgb: 0xefefef)
let ILR_GRAY = UIColor(rgb: 0xbbbcbf)
let ILR_DARK_GRAY = UIColor(rgb: 0x7f8183)
let ILR_BLACK = UIColor(rgb: 0x1d1d1b)
let ILR_LIGHT_RED = UIColor(rgb: 0xfbd2c4)
let ILR_RED = UIColor(rgb: 0xed4442)

///////////////////////////////
// MARK: Colors
///////////////////////////////

let RMBT_DARK_COLOR     = ILR_WHITE
let RMBT_TINT_COLOR     = ILR_RED

let MEASUREMENT_SCREEN_BACKGROUND_COLOR = ILR_WHITE

let MEASUREMENT_START_BUTTON_COLOR = ILR_RED
let MEASUREMENT_START_BUTTON_DURING_MEASUREMENT_COLOR = ILR_GRAY

let MEASUREMENT_GAUGE_BASE_COLOR = ILR_LIGHT_GRAY
let MEASUREMENT_GAUGE_PROGRESS_COLOR = ILR_RED
let MEASUREMENT_GAUGE_VALUE_COLOR = ILR_RED
let MEASUREMENT_GAUGE_TEXT_COLOR = ILR_WHITE

let MEASUREMENT_REPORT_BUTTON_COLOR = ILR_GRAY

let ICON_TINT_COLOR = ILR_RED
let ICON_INACTIVE_TINT_COLOR = ILR_LIGHT_GRAY

//

let NAVIGATION_SELECTED_BACKGROUND_VIEW_COLOR: UIColor? = ILR_LIGHT_RED
let NAVIGATION_BACKGROUND_COLOR = ILR_RED
let NAVIGATION_TEXT_COLOR = ILR_WHITE

let NAVIGATION_USE_TINT_COLOR = true

let TEXT_COLOR = ILR_BLACK //ILR_DARK_GRAY

let COLOR_CHECK_GREEN   = UIColor(rgb: 0x30C80B)
let COLOR_CHECK_YELLOW  = UIColor(rgb: 0xFECB1D)
let COLOR_CHECK_RED     = UIColor(rgb: 0xA11B07)
